# fly.toml app configuration file generated for full-stack-open-pokedex-damp-wave-1975 on 2025-03-08T21:06:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-damp-wave-1975'
primary_region = 'fra'

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  strategy = "canary"
    max_unavailable = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
